"""add missing indexes for SaaS performance

Revision ID: 342de95416fc
Revises: 4bb2cf15d957
Create Date: 2026-03-03 15:40:12.484276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '342de95416fc'
down_revision: Union[str, Sequence[str], None] = '4bb2cf15d957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Only add missing indexes, do not drop tables or constraints
    op.create_index(op.f('ix_analysis_created_at'), 'analysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_user_id'), 'analysis', ['user_id'], unique=False)
    op.create_index(op.f('ix_app_users_organization_id'), 'app_users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organizations_domain'), 'organizations', ['domain'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_domain'), table_name='organizations')
    op.create_unique_constraint(op.f('organizations_domain_key'), 'organizations', ['domain'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_app_users_organization_id'), table_name='app_users')
    op.create_index(op.f('ix_users_supabase_id'), 'app_users', ['supabase_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'app_users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'app_users', ['email'], unique=False)
    op.drop_index(op.f('ix_analysis_user_id'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_created_at'), table_name='analysis')
    op.create_table('specializations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('centroid', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('sample_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('specializations_industry_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('specializations_pkey'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('specialization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('jobs_industry_id_fkey')),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], name=op.f('jobs_specialization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_table('industries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('centroid', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('sample_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('industries_domain_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('industries_pkey'))
    )
    op.create_table('job_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('job_embeddings_pkey')),
    sa.UniqueConstraint('job_hash', name=op.f('job_embeddings_job_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('domains',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('centroid', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('sample_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('domains_pkey')),
    sa.UniqueConstraint('name', name=op.f('domains_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
