"""initial schema

Revision ID: 01cc20e2945c
Revises: 
Create Date: 2026-03-03 14:26:32.995993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01cc20e2945c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    This is a baseline migration generated when the project already had
    tables present in the database. The auto‑generated version attempted to
    drop those tables because they are not tracked by SQLAlchemy's
    ``Base.metadata`` (they're managed via raw SQL in ``setup_db.py``).

    We intentionally leave this migration as a no-op so that Alembic can
    stamp the database without altering anything. Future migrations should
    explicitly create or modify tables declared by the ORM.
    """
    # no operations; the existing schema is already correct for our
    # current models (users and analysis) and the legacy tables are handled
    # outside of Alembic.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('centroid', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('sample_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('specializations_industry_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('specializations_pkey'))
    )
    op.create_table('domains',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('centroid', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('sample_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('domains_pkey')),
    sa.UniqueConstraint('name', name=op.f('domains_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('industries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('centroid', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('sample_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('industries_domain_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('industries_pkey'))
    )
    op.create_table('job_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('job_embeddings_pkey')),
    sa.UniqueConstraint('job_hash', name=op.f('job_embeddings_job_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('specialization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('jobs_industry_id_fkey')),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], name=op.f('jobs_specialization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    # ### end Alembic commands ###
