"""add organizations + role FK to app_users

Revision ID: 4bb2cf15d957
Revises: 2a2ae8f5f8c3
Create Date: 2026-03-03 14:57:56.116500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bb2cf15d957'
down_revision: Union[str, Sequence[str], None] = '2a2ae8f5f8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create organizations table only; do not drop legacy tables here.
    op.create_table(
        'organizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('domain', sa.String(), nullable=False),
        sa.Column('plan_type', sa.String(), nullable=True),
        sa.Column('daily_usage', sa.Integer(), nullable=True),
        sa.Column('monthly_usage', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('domain')
    )

    # Add role and organization FK to app_users. Avoid touching other tables.
    op.add_column('app_users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('app_users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=False)
    op.create_index(op.f('ix_app_users_id'), 'app_users', ['id'], unique=False)
    op.create_index(op.f('ix_app_users_supabase_id'), 'app_users', ['supabase_id'], unique=True)
    op.create_foreign_key(None, 'app_users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_users', type_='foreignkey')
    op.drop_index(op.f('ix_app_users_supabase_id'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_id'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.create_index(op.f('ix_users_supabase_id'), 'app_users', ['supabase_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'app_users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'app_users', ['email'], unique=False)
    op.drop_column('app_users', 'organization_id')
    op.drop_column('app_users', 'role')
    op.create_table('specializations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('centroid', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('sample_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('specializations_industry_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('specializations_pkey'))
    )
    op.create_table('job_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('job_embeddings_pkey')),
    sa.UniqueConstraint('job_hash', name=op.f('job_embeddings_job_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('domains',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('centroid', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('sample_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('domains_pkey')),
    sa.UniqueConstraint('name', name=op.f('domains_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('specialization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('jobs_industry_id_fkey')),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], name=op.f('jobs_specialization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_table('industries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('centroid', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('sample_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('industries_domain_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('industries_pkey'))
    )
    op.drop_table('organizations')
    # ### end Alembic commands ###
